# Welcome to Jekyll!
#

# Site settings
title: Black Sea Networks
description: |
  A collaborative initiative 
  to investigate the Black Sea <br /> 
  as a hub of cultural, political,
  and historical interest.
owner: Columbia University Slavic Department
first_published: 2016 # if migrating another site, the year of your first publish
email: vbi1@columbia.edu
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blackseanetworks.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
